# Generated by Django 2.1.1 on 2018-09-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0002_auto_20180925_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoseletivo',
            name='ano_letivo',
            field=models.PositiveIntegerField(verbose_name='Ano letivo'),
        ),
    ]
