# Generated by Django 2.1.1 on 2018-09-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0004_auto_20180925_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processoseletivo',
            name='matriz_curso',
            field=models.CharField(max_length=256, verbose_name='Matriz/Curso'),
        ),
    ]
