# Generated by Django 2.1.1 on 2018-09-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0012_oferta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processoseletivo',
            name='aluno_especial',
        ),
        migrations.RemoveField(
            model_name='processoseletivo',
            name='conclusao_intercambio',
        ),
        migrations.RemoveField(
            model_name='processoseletivo',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='processoseletivo',
            name='forma_ingresso',
        ),
        migrations.RemoveField(
            model_name='processoseletivo',
            name='linha_pesquisa',
        ),
        migrations.RemoveField(
            model_name='processoseletivo',
            name='matriz_curso',
        ),
        migrations.RemoveField(
            model_name='processoseletivo',
            name='numero_pasta',
        ),
        migrations.RemoveField(
            model_name='processoseletivo',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='processoseletivo',
            name='polo',
        ),
        migrations.RemoveField(
            model_name='processoseletivo',
            name='turno',
        ),
        migrations.AddField(
            model_name='processoseletivo',
            name='numero_ano',
            field=models.CharField(default=1, max_length=100, verbose_name='Número / Ano'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processoseletivo',
            name='uo',
            field=models.CharField(default=1, max_length=100, verbose_name='Unidade organizacional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processoseletivo',
            name='url',
            field=models.URLField(default=1, max_length=300, verbose_name='Endereço do edital'),
            preserve_default=False,
        ),
    ]
