# Generated by Django 2.1.1 on 2018-09-26 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0006_auto_20180926_1345'),
        ('processo_seletivo', '0014_ofertapolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='polo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dominio.Polo'),
            preserve_default=False,
        ),
    ]
