# Generated by Django 2.1.1 on 2018-09-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0015_oferta_polo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='polo',
        ),
    ]
