# Generated by Django 2.1.1 on 2018-09-26 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0007_campus_curso'),
        ('processo_seletivo', '0016_remove_oferta_polo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertapolo',
            name='oferta',
        ),
        migrations.RemoveField(
            model_name='ofertapolo',
            name='polo',
        ),
        migrations.AddField(
            model_name='oferta',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dominio.Campus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dominio.Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='polo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dominio.Polo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oferta',
            name='turno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dominio.Turno'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='OfertaPolo',
        ),
    ]
