# Generated by Django 2.1.1 on 2018-09-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0017_auto_20180926_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='nome',
            field=models.CharField(help_text='Digite o nome do processo seletivo', max_length=256, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='ano_letivo',
            field=models.PositiveIntegerField(help_text='Digite o ano', verbose_name='Ano letivo'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='identificacao',
            field=models.CharField(help_text='Digite sua identificação', max_length=256, verbose_name='Identificação'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='numero_ano',
            field=models.CharField(help_text='Digite o número e o ano do edital', max_length=100, verbose_name='Número / Ano'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='uo',
            field=models.CharField(help_text='Digite a unidade organizacional', max_length=100, verbose_name='Unidade organizacional'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='url',
            field=models.URLField(help_text='Informe o LINK onde está o edital', max_length=300, verbose_name='Endereço do edital'),
        ),
    ]
