# Generated by Django 2.1.1 on 2018-09-27 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('processo_seletivo', '0018_auto_20180927_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(help_text='Informe o arquivo de importação', upload_to='', verbose_name='Arquivo de importação')),
                ('processo_seletivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='processo_seletivo.ProcessoSeletivo')),
            ],
            options={
                'verbose_name': 'Arquivo de importação',
                'verbose_name_plural': 'Arquivos de importações',
                'ordering': ['arquivo'],
            },
        ),
    ]
