# Generated by Django 2.1.1 on 2018-09-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0008_auto_20180927_1621'),
        ('processo_seletivo', '0020_auto_20180927_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selecionado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dominio.Convenio')),
                ('estado_civil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dominio.EstadoCivil')),
                ('forma_ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dominio.FormaIngresso')),
            ],
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='numero_ano',
            field=models.CharField(help_text='Digite o número e o ano do edital. Ex.: 36/2018', max_length=100, verbose_name='Número / Ano'),
        ),
        migrations.AlterField(
            model_name='processoseletivo',
            name='uo',
            field=models.CharField(help_text='Ex.: DG-EAD/IFRN', max_length=100, verbose_name='Unidade organizacional'),
        ),
    ]
