# Generated by Django 2.1.1 on 2018-09-27 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0008_auto_20180927_1621'),
        ('processo_seletivo', '0021_auto_20180927_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecionado',
            name='data_nascimento',
            field=models.DateField(default=1, verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selecionado',
            name='email_resp',
            field=models.EmailField(blank=True, max_length=50, null=True, unique=True, verbose_name='E-mail do responsável'),
        ),
        migrations.AddField(
            model_name='selecionado',
            name='foto',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='', verbose_name='Arquivo de importação'),
        ),
        migrations.AddField(
            model_name='selecionado',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='selecionado',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nome da mãe'),
        ),
        migrations.AddField(
            model_name='selecionado',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nome do pai'),
        ),
        migrations.AddField(
            model_name='selecionado',
            name='nome_resp',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nome do responsável'),
        ),
        migrations.AddField(
            model_name='selecionado',
            name='nome_social',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Nome social'),
        ),
        migrations.AddField(
            model_name='selecionado',
            name='pai_falecido',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Pai falecido?'),
        ),
        migrations.AddField(
            model_name='selecionado',
            name='sexo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dominio.Sexo'),
        ),
    ]
