# Generated by Django 2.1.1 on 2018-09-24 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('codigo_suap', models.CharField(max_length=200, verbose_name='Código SUAP')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexo',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
    ]
