# Generated by Django 2.1.1 on 2018-09-25 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('codigo_suap', models.CharField(blank=True, max_length=200, null=True, verbose_name='Código SUAP')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Estado civil',
                'verbose_name_plural': 'Estados civis',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.CreateModel(
            name='NivelEnsino',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Nível de Ensino',
                'verbose_name_plural': 'Níveis de Ensino',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.CreateModel(
            name='OrgaoEmissor',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Órgão Emissor',
                'verbose_name_plural': 'Órgãos Emissores',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.CreateModel(
            name='PaisOrigem',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Pais de Origem',
                'verbose_name_plural': 'Paises de Origem',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Raça',
                'verbose_name_plural': 'Raças',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.CreateModel(
            name='TipoCertidao',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Tipo de Certidão',
                'verbose_name_plural': 'Tipos de Certidões',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Tipo do Documento',
                'verbose_name_plural': 'Tipos do Documentos',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.CreateModel(
            name='TipoInstituicao',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Tipo de Instituição',
                'verbose_name_plural': 'Tipos de Instituições',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.CreateModel(
            name='TipoSanguineo',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Tipo sanguíneo',
                'verbose_name_plural': 'Tipos sanguíneos',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Unidade Federativa',
                'verbose_name_plural': 'Unidades Federativas',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.CreateModel(
            name='ZonaResidencial',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Zona Residencial',
                'verbose_name_plural': 'Zonas Residenciais',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
    ]
