# Generated by Django 2.1.1 on 2018-09-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polo',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Polo',
                'verbose_name_plural': 'Polos',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Documento', 'verbose_name_plural': 'Tipos de Documentos'},
        ),
    ]
