# Generated by Django 2.1.1 on 2018-09-24 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0006_nivelensino'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeFederativa',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Unidade Federativa',
                'verbose_name_plural': 'Unidade Federativa',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.AlterModelOptions(
            name='nivelensino',
            options={'verbose_name': 'Nível de Ensino', 'verbose_name_plural': 'Nível de Ensino'},
        ),
    ]
