# Generated by Django 2.1.1 on 2018-09-24 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0007_auto_20180924_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaisOrigem',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Pais de Origem',
                'verbose_name_plural': 'Pais de Origem',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
    ]
