# Generated by Django 2.1.1 on 2018-09-27 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0007_campus_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgaoemissor',
            options={'ordering': ['nome'], 'verbose_name': 'Orgão emissor', 'verbose_name_plural': 'Orgãos emissores'},
        ),
        migrations.AlterModelOptions(
            name='paisorigem',
            options={'ordering': ['nome'], 'verbose_name': 'País de origem', 'verbose_name_plural': 'Países de origens'},
        ),
    ]
