# Generated by Django 2.1.1 on 2018-09-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0011_zonaresidencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoConclusao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField(verbose_name='Ano')),
            ],
            options={
                'ordering': ['ano'],
            },
        ),
    ]
