# Generated by Django 2.1.1 on 2018-09-25 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0012_anoconclusao'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dominio.Base')),
            ],
            options={
                'verbose_name': 'Tipo do Documento',
                'verbose_name_plural': 'Tipo do Documento',
                'ordering': ['nome'],
            },
            bases=('dominio.base',),
        ),
        migrations.AlterModelOptions(
            name='anoconclusao',
            options={'verbose_name': 'Ano Conclusão', 'verbose_name_plural': 'Ano Conclusão'},
        ),
    ]
