# Generated by Django 2.1.1 on 2018-09-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0012_anoconclusao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoconclusao',
            options={'verbose_name': 'Ano Conclusão', 'verbose_name_plural': 'Ano Conclusão'},
        ),
        migrations.AlterModelOptions(
            name='estadocivil',
            options={'ordering': ['nome'], 'verbose_name': 'Estado civil', 'verbose_name_plural': 'Estados civis'},
        ),
        migrations.AlterModelOptions(
            name='nivelensino',
            options={'ordering': ['nome'], 'verbose_name': 'Nível de Ensino', 'verbose_name_plural': 'Níveis de Ensino'},
        ),
        migrations.AlterModelOptions(
            name='orgaoemissor',
            options={'ordering': ['nome'], 'verbose_name': 'Órgão Emissor', 'verbose_name_plural': 'Órgãos Emissores'},
        ),
        migrations.AlterModelOptions(
            name='paisorigem',
            options={'ordering': ['nome'], 'verbose_name': 'Pais de Origem', 'verbose_name_plural': 'Paises de Origem'},
        ),
        migrations.AlterModelOptions(
            name='raca',
            options={'ordering': ['nome'], 'verbose_name': 'Raça', 'verbose_name_plural': 'Raças'},
        ),
        migrations.AlterModelOptions(
            name='sexo',
            options={'ordering': ['nome'], 'verbose_name': 'Sexo', 'verbose_name_plural': 'Sexos'},
        ),
        migrations.AlterModelOptions(
            name='tipocertidao',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Certidão', 'verbose_name_plural': 'Tipos de Certidões'},
        ),
        migrations.AlterModelOptions(
            name='tipoinstituicao',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Instituição', 'verbose_name_plural': 'Tipos de Instituições'},
        ),
        migrations.AlterModelOptions(
            name='tiposanguineo',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo sanguíneo', 'verbose_name_plural': 'Tipos sanguíneos'},
        ),
        migrations.AlterModelOptions(
            name='unidadefederativa',
            options={'ordering': ['nome'], 'verbose_name': 'Unidade Federativa', 'verbose_name_plural': 'Unidades Federativas'},
        ),
        migrations.AlterModelOptions(
            name='zonaresidencial',
            options={'ordering': ['nome'], 'verbose_name': 'Zona Residencial', 'verbose_name_plural': 'Zonas Residenciais'},
        ),
        migrations.AlterField(
            model_name='base',
            name='codigo_suap',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código SUAP'),
        ),
    ]
