# Generated by Django 2.1.1 on 2018-09-25 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dominio', '0013_auto_20180924_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnoConclusao',
        ),
    ]
